apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-container
        image: dpkorcle/auth:#{BUILD_NUMBER}#
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
