apiVersion: apps/v1
kind: Deployment
metadata:
  name: books-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-app
  template:
    metadata:
      labels:
        app: books-app
    spec:
      containers:
      - name: books-container
        image: dpkorcle/books:#{BUILD_NUMBER}#
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
